name: Verificar assinaturas

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - "assinaturas/**/*.asc"
      - "bitdevs.json"
      - "assinantes.json"
      - "chaves/**/*.asc"
      - "flake.nix"
      - ".github/workflows/assinantes.yml"
  push:
    branches: [master]
    paths:
      - "assinaturas/**/*.asc"
      - "bitdevs.json"
      - "assinantes.json"
      - "chaves/**/*.asc"
      - "flake.nix"
      - ".github/workflows/assinantes.yml"

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run .#verificar-assinaturas
