name: Validate bitdevs.json

on:
  pull_request:
    paths: [bitdevs.json, flake.nix]
  push:
    branches: [master]
    paths: [bitdevs.json, flake.nix]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check
